; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform =      espressif32
board =         esp32-s3-devkitc-1
framework =     arduino
monitor_speed = 115200
monitor_filters = exc
board_upload.flash_size   = 4MB
board_build.flash_size    = 4MB
board_build.flash_mode    = dio
board_build.arduino.memory_type = dio_qspi
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
build_flags            = 
    -DARDUINO_USB_MODE=1 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Ofast 
    -ffunction-sections 
    -fdata-sections 
    -fno-exceptions 
    -fno-rtti 
    -funroll-loops 
    -fjump-tables 
    -ftree-switch-conversion 
    -fno-tree-vectorize 
    -frename-registers 
    -fno-plt 
    -mlongcalls 
    -DOPTIMIZATION_FLAGS
    -Wl,--gc-sections
    -Wl,-flto
    -Wl,-u,app_main
    

lib_deps = 
    adafruit/Adafruit GFX Library@^1.11.0
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    robtillaart/PCF8574@^0.4.1
    adafruit/Adafruit ADS1X15@^2.5.0
    qqqlab/ESP32_SoftWire@^1.0.2
    stevemarple/AsyncDelay@^1.1.2
    littlefs
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
